# Generated by Django 4.2.10 on 2026-02-25 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='出版社/版本名稱')),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('ES', '國小'), ('JH', '國中'), ('SH', '高中')], default='ES', max_length=2, verbose_name='學校類別')),
                ('district', models.CharField(choices=[('桃園區', '桃園區'), ('中壢區', '中壢區'), ('平鎮區', '平鎮區'), ('八德區', '八德區'), ('楊梅區', '楊梅區'), ('蘆竹區', '蘆竹區'), ('大園區', '大園區'), ('龜山區', '龜山區'), ('龍潭區', '龍潭區'), ('大溪區', '大溪區'), ('新屋區', '新屋區'), ('觀音區', '觀音區'), ('復興區', '復興區')], default='桃園區', max_length=10, verbose_name='行政區')),
                ('name', models.CharField(max_length=255, verbose_name='學校名稱')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTextbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(verbose_name='學年度')),
                ('grade', models.IntegerField(verbose_name='年級')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.school', verbose_name='學校名稱')),
                ('subject_chinese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chinese_books', to='books.publisher', verbose_name='國語版本')),
                ('subject_english', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='english_books', to='books.publisher', verbose_name='英文版本')),
                ('subject_math', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='math_books', to='books.publisher', verbose_name='數學版本')),
                ('subject_science', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='science_books', to='books.publisher', verbose_name='生活自然版本')),
                ('subject_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_books', to='books.publisher', verbose_name='社會版本')),
            ],
            options={
                'verbose_name': '學校用書紀錄',
                'verbose_name_plural': '學校用書紀錄',
                'unique_together': {('school', 'academic_year', 'grade')},
            },
        ),
    ]
