# Generated by Django 4.2.10 on 2026-02-25 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '行政區', 'verbose_name_plural': '行政區'},
        ),
    ]
