# Generated by Django 4.2.10 on 2026-02-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_school_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTexbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=5)),
                ('sub_chinese', models.CharField(max_length=20)),
                ('sub_math', models.CharField(max_length=20)),
                ('sub_science', models.CharField(max_length=20)),
                ('sub_social', models.CharField(max_length=20)),
                ('sub_english', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
            },
        ),
        migrations.AlterUniqueTogether(
            name='schooltextbook',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='schooltextbook',
            name='school',
        ),
        migrations.RemoveField(
            model_name='schooltextbook',
            name='subject_chinese',
        ),
        migrations.RemoveField(
            model_name='schooltextbook',
            name='subject_english',
        ),
        migrations.RemoveField(
            model_name='schooltextbook',
            name='subject_math',
        ),
        migrations.RemoveField(
            model_name='schooltextbook',
            name='subject_science',
        ),
        migrations.RemoveField(
            model_name='schooltextbook',
            name='subject_social',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='SchoolTextbook',
        ),
    ]
