# Generated by Django 4.2.10 on 2026-02-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_schooltexbook_alter_schooltextbook_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolTexbook',
        ),
    ]
