# Generated by Django 4.2.10 on 2026-02-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0004_delete_schooltexbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileImportTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('last_modified', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTexbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=5)),
                ('sub_chinese', models.CharField(max_length=20)),
                ('sub_math', models.CharField(max_length=20)),
                ('sub_science', models.CharField(max_length=20)),
                ('sub_social', models.CharField(max_length=20)),
                ('sub_english', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
            },
        ),
    ]
