# Generated by Django 4.2.10 on 2026-02-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltexbook',
            name='grade_num',
            field=models.IntegerField(default=0),
        ),
    ]
